apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: svvywfwrk-python 
  janus-idp.io/tekton: svvywfwrk-python
  backstage.io/kubernetes-id: svvywfwrk-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: svvywfwrk-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml