apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: svvywfwrk-python-gitops
  description: This is GitOps manifest for svvywfwrk-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=svvywfwrk-python
    backstage.io/kubernetes-id: svvywfwrk-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: svvywfwrk-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:svvywfwrk-python
